# USAGE: 
#  $ ansible-playbook -e "rf=<IP1> sut=<IP2> runtime=120 interval=5 numpar=128" ./<file>.yml
#
#
# PLAYS:
#       Localhost: Parse and set cmdline vars
#       SUT: Start workload on SUT as async task, store cpuinfo vars
#       Localhost: Start power script as async task
#       SUT: poll async-Workload PID complete, save SUT-results
#       Localhost: Stop pwr script, write logfile w/SUT-results, cleanup
#       SUT: cleanup async-Workload artifacts
#
# NOTE: jobfiles for both async tasks (SUT & localhost) are manually
#       cleaned up with use of 'async-status': mode 'cleanup'.
# SUT Server login credentials are set in PLAY 2 
# Redfish Server login credentials are set in PLAY 3 
############################################################################
---
#########
# PLAY 1: Start with some housekeeping tasks
- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Verify all req'd extra-vars are defined
      ansible.builtin.assert:
        that:
          - rf != ""
          - sut != ""
          - runtime != ""
          - interval != ""
          - numpar != ""

# Allows use of 'sut' var as host
    - add_host:
        name: "{{ sut }}"

#########
# PLAY 2: Gather SUT facts and Start workload on SUT
# NOTE: this workload does not represent a fixed amount of compute work
#   SO not a good basis for normalizing results across varying cpu's
# Start workload on SUT (server under test) as async task
#- hosts: sut_host
- hosts: "{{ sut }}"
  remote_user: root
  become: false
  gather_facts: false
# Pad asynctime for Workload to ensure adequate wall clocktime
  vars:
    asynctime: "{{ (runtime * 2)|int|abs }}"
    ROOT_PASSWORD: 100yard-
  tasks:
    - name: set sut_host root password
      set_fact:
        ansible_password: "{{ ROOT_PASSWORD }}"

    - name: Record CPU Model
      shell:
        cmd: |
          lscpu | grep '^Model name:' | sed -r 's/^Model name:[ \t]*//'
      register: cpumodel

    - name: Record number of CPU cores
      shell:
        cmd: |
          lscpu | awk '/^CPU\(s\):/{print $2}'
      register: numcores

    - name: Record number of CPU sockets
      shell:
        cmd: |
          lscpu | awk '/^Socket\(s\):/{print $2}'
      register: numsockets

    - name: Record Linux kernel version
      shell: uname -r
      register: kversion

    - name: set sut_host vars from this PLAY for later use
      set_fact:
        cpu_model: "{{ cpumodel.stdout }}"
        num_cores: "{{ numcores.stdout }}"
        num_sockets: "{{ numsockets.stdout }}"
        k_version: "{{ kversion.stdout }}"

    - name: Run Workload
#      Requires gather_facts to dynamically set {{ numpar }}
# Specify -bytes' to ensure runtime (only one is performed)
      shell:
        cmd: |
          openssl speed -evp sha256 -bytes 16384 -seconds "{{ runtime }}" -multi "{{ numpar }}" 2>/dev/null | tail -1 | awk '{print $2}'
      async: "{{ asynctime }}"
      poll: 0
      register: workload

    - name: wait for Workload to have started as async task
      ansible.builtin.async_status:
        jid: "{{ workload.ansible_job_id }}"
        mode: status
      register: async_workload
      until: async_workload.started
      retries: 15
      delay: 1
 
# Record the PID of Workload for later polling (wait_for in PLAY 4)
# NOTE: Workload process-name is HARD-CODED
    - name: Get Workload PID
      command: "pgrep -n openssl"
      register: workloadPID

    - name: set sut_host workloadPID var for later use
      set_fact:
        workload_pid: "{{ workloadPID.stdout }}"

#########
# PLAY 3: Start pwr monitoring script on localhost as async task
- hosts: localhost
  become: false
  gather_facts: false
# Pad asynctime to ensure adequate wall clocktime
  vars:
    ansible_python_interpreter: /usr/bin/python3
    asynctime: "{{ (runtime * 2)|int|abs }}"
    pwr_script: rfChassis.py
    rfSvr: "{{ rf }}"
    rfUser: "root"
#    rfUser: "ADMIN"
    rfPasswd: "100yard-"
    outfile: "{{ numpar }}_test.log"

  tasks:
    - name: Start power monitoring script as async task
      shell:
        cmd: |
          ./{{ pwr_script }} {{ rfSvr }} {{ rfUser }} {{ rfPasswd }} > {{ outfile }}
      async: "{{ asynctime }}"
      poll: 0
      register: pwr_monitor
    
# Verify pwr_script is running before moving forward (pgrep)
    - name: Brief pause and then Get power script PID - to later PKILL
      shell:
        cmd: |
          sleep 0.5
          pgrep {{ pwr_script }}
      register: pwr_pid

    - name: print pwr_pid
      ansible.builtin.debug:
        msg: "{{ pwr_script }} with PID {{ pwr_pid.stdout }} found"

    - name: set ansible_job_id from this PLAY for later Cleanup
      set_fact:
        pwrmon_jid: "{{ pwr_monitor.ansible_job_id }}"
        
###########
# PLAY 4: SUT wait for Workload (async) to complete
- hosts: "{{ sut }}"
  remote_user: root
  become: false
  gather_facts: false
  vars:
    ROOT_PASSWORD: 100yard-
  tasks:
    - name: wait_for workload_pid to finish 
      ansible.builtin.wait_for:
         path: "/proc/{{ hostvars[sut].workload_pid }}/status"
         state: absent

    - name: Workload finished - use async_status to record STDOUT
      ansible.builtin.async_status:
        jid: "{{ hostvars[sut].workload.ansible_job_id }}"
        mode: status
      register: async_job
      until: async_job.finished
      retries: 10
      delay: 1

    - name: set Workload STDOUT/result as sut_host var for later use
      set_fact:
        workload_stdout: "{{ async_job.stdout }}"

#########
# PLAY 5: SUT Workload complete, kill pwr script and record results
- hosts: localhost
  become: false
  gather_facts: false
  vars:
    pwr_script: rfChassis.py
    outfile: "{{ numpar }}_test.log"
  tasks:
    - name: Kill power script PID with SIGINT
      shell:
        cmd: |
          pkill -e -SIGINT {{ pwr_script }}
      register: pkill_res
      
#    - name: DEBUG
#     ansible.builtin.debug:
#        msg: "PKILL {{ pkill_res.stdout }}"

    - name: Sleep 2s to allow power script to complete writing logfile
      command: "sleep 2"
      
    - name: append SUT facts and Workload rate to logfile
      ansible.builtin.blockinfile:
        path: "{{ outfile }}"
        create: no
        insertafter: EOF
        marker: "#{mark} SUT STATS"
        block: |
          "kernel-version : {{ hostvars[sut].k_version }}"
          "CPU-Model : {{ hostvars[sut].cpu_model }}"
          "numcores : {{ hostvars[sut].num_cores }}"
          "numsockets : {{ hostvars[sut].num_sockets }}"
          "EVP Rate for -multi {{ numpar }} : {{ hostvars[sut].workload_stdout }}"
      
#    - name: wrote pwr_script and SUT Workload output to logfile
#      ansible.builtin.debug:
#       msg: "Output written {{ outfile }}"

# CLEANUP async task manually: power_script (localhost)
    - name: cleanup pwr_script async task artifacts
      ansible.builtin.async_status:
        jid: "{{ pwrmon_jid }}"
        mode: '{{ item }}'
      register: job
      until: job.finished or (job.erased is defined)
      retries: 5
      delay: 1
      loop:
        - 'status'
        - 'cleanup'

#########
# PLAY 6: SUT cleanup Workload async task artifacts
- hosts: "{{ sut }}"
  remote_user: root
  become: false
  gather_facts: false
  vars:
    ROOT_PASSWORD: 100yard-
    outfile: "{{ numpar }}_test.log"
  tasks:
    - name: Workload cleanup - async task
      ansible.builtin.async_status:
        jid: "{{ hostvars[sut].workload.ansible_job_id }}"
        mode: cleanup

    - name: mark DONE
      ansible.builtin.debug:
        msg: "DONE. Logfile written to: {{ outfile }}"
        
# END

